### ISSUE TITLE
extension does not work

### ISSUE THREAD

**Issue by Rainbow-Web-com** [th3james/nova-open-on-github#1]
Hello,

unfortunately the extension does not work. When I want to open a file via Nova version 8.3 in github, just nothing happens.

Any idea, or the extension is no longer developed?

**Comment by th3james** [comment]
Hi @Rainbow-Web-com

Sorry for the extremely delayed response, I stopped using Nova for a few years and didn't have time to maintain the extension.

I have just released a complete re-write of this project which now better respects user ENVs, in addition to being a lot faster. If you are able to test and report back whether you are still seeing this issue, that would be appreciated.
